### ISSUE TITLE
SimChat post messages

### ISSUE THREAD

**Issue by zippy** [holochain/lib3h#161]
As an HBC users I can post a message that other peers will ALL see (as opposed to direct messages).

- [ ] HBC can create time anchors #64 
- [ ] HBC can post time-anchored messages to DHT #65 
- [ ] HBC polls for messages in time blocks #66 

Acceptance Criteria:

- users can send messages using `post`  from the hbc command line
- all other online users see those messages pop up
- users that come online see previously posted message
